// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Board struct {
	ID          uuid.UUID
	Title       string
	Description string
	Owner       uuid.UUID
	TeamID      uuid.UUID
	CreatedAt   pgtype.Timestamp
}

type Status struct {
	ID        uuid.UUID
	Title     string
	BoardID   uuid.UUID
	CreatedAt pgtype.Timestamp
}

type StatusesNextStatus struct {
	StatusID   uuid.UUID
	NextStatus uuid.UUID
}

type StatusesPreviousStatus struct {
	StatusID       uuid.UUID
	PreviousStatus uuid.UUID
}

type Task struct {
	ID          uuid.UUID
	Title       string
	Description string
	Creator     uuid.UUID
	Asigned     uuid.UUID
	StatusID    uuid.UUID
	CreatedAt   pgtype.Timestamp
}

type Team struct {
	ID          uuid.UUID
	Title       string
	Description string
	Owner       uuid.UUID
	CreatedAt   pgtype.Timestamp
}

type TeamsUser struct {
	TeamID uuid.UUID
	UserID uuid.UUID
}

type User struct {
	ID        uuid.UUID
	Email     string
	CreatedAt pgtype.Timestamp
}
